# Generated by Django 6.0 on 2025-12-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pyment_method',
            field=models.CharField(choices=[('cod', 'Chas on delivery'), ('stripe', 'Stripe')], default='cod', max_length=20),
            preserve_default=False,
        ),
    ]
