# Generated by Django 6.0 on 2025-12-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_pyment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pyment_method',
            new_name='payment_method',
        ),
    ]
